name: build
on:
  push:
    paths-ignore:
      - 'README.md'
  deployment:
    branches:
      - master

jobs:
  pakcer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.x'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python3 -m pip install ansible boto boto3

      - name: Set Ansible Python interpreter
        run: |
          ANSIBLE_PYTHON_INTERPRETER=`which python`
          echo $ANSIBLE_PYTHON_INTERPRETER
          echo "ANSIBLE_PYTHON_INTERPRETER=${ANSIBLE_PYTHON_INTERPRETER}" >> $GITHUB_ENV

      - name: Set environment variable with timestamp for making sure GHA would create unique AWS resources
        run: |
          TIMESTAMP=$(date --date "9 hours" "+%Y%m%d_%H%M%S")
          echo "AWSIAM_USER=packer_redmica_restore_gce_${TIMESTAMP}" >> $GITHUB_ENV
          echo "AWSIAM_POLICY_NAME=packer_redmica_restore_gce_${TIMESTAMP}" >> $GITHUB_ENV

      - name: Retrieve Ansible playbook for creating AWS access key
        uses: actions/checkout@v2
        with:
          repository: ansible-playbooks-mamono210/awsiam
          path: awsiam

      - name: Create AWS access key
        run: |
          cd awsiam
          ansible-galaxy install -r roles/requirements.yml
          ansible-playbook -i localhost, -c local \
          -e "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -e "aws_region=ap-northeast-1" \
          -e "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -e "awsiam_policy_file_path=../iam_policy.json" \
          -e "awsiam_policy_name=${AWSIAM_POLICY_NAME}" \
          -e "awsiam_user=${AWSIAM_USER}" \
          -e "awsiam_user_state=present" \
          -e "linux_group=runner" \
          -e "linux_user=runner" \
          -e "linux_userhome=/home/runner" \
          install.yml

      - name: Set AWS credentials to GitHub Actions environment variables
        run: |
          AWS_ACCESS_KEY_ID=`cat ~/.aws/credentials | grep aws_access_key_id | awk '{print $3}'`
          AWS_SECRET_ACCESS_KEY=`cat ~/.aws/credentials | grep aws_secret_access_key | awk '{print $3}'`
          AWS_REGION=`cat ~/.aws/config | grep region | awk '{print $3}'`

          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV
          echo "AWS_REGION=${AWS_REGION}" >> $GITHUB_ENV

          echo "::add-mask::$AWS_ACCESS_KEY_ID"
          echo "::add-mask::$AWS_SECRET_ACCESS_KEY"
          echo "::add-mask::$AWS_REGION"

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get install packer

      - name: Retrieve Ansible playbooks
        run: |
          git clone https://github.com/ansible-playbooks-mamono210/aws-s3.git
          git clone https://github.com/ansible-playbooks-mamono210/redmine_restore.git

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: 'buoyant-world-263612'
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_ENCODED }}
          export_default_credentials: true

      - name: Set golden image name to environment variables
        run: |
          GIT_VERSION=$(echo ${{ matrix.git-version}} | sed 's/\.//g')

          SOURCE_IMAGE=$(gcloud compute images list \
          --format="value(NAME)" \
          --filter="name~'redmica-golden-image'" \
          --sort-by=~creationTimestamp \
          --limit=1 \
          | awk '{print $1}')
          echo "SOURCE_IMAGE=${SOURCE_IMAGE}" >> $GITHUB_ENV

      - name: Execute pakcer build command
        run: |
          GIT_VERSION=$(echo ${{ matrix.git-version}} | sed 's/\.//g')
          IMAGE_NAME="redmica-restored-${GIT_VERSION}-`date --date \"9 hours\" \"+%Y-%m%d-%H%M%S\"`"

          packer build \
          -var "aws_access_key=${AWS_ACCESS_KEY_ID}" \
          -var "aws_region=${AWS_DEFAULT_REGION}" \
          -var "aws_secret_key=${AWS_SECRET_ACCESS_KEY}" \
          -var "image_name=${IMAGE_NAME}" \
          -var "local_file_name=${{ secrets.AWS_S3_OBJECT_NAME }}" \
          -var "project_id=buoyant-world-263612" \
          -var "s3_bucket=${{ secrets.AWS_S3_BUCKET_NAME }}" \
          -var "s3_object_name=${{ secrets.AWS_S3_OBJECT_NAME }}" \
          -var "source_image=${SOURCE_IMAGE}" \
          -var "ssh_username=packer" \
          -var "working_dir=/tmp/s3" \
          -var "zone=asia-northeast2-a" \
          build.json

      - name: Delete AWS access key
        run: |
          cd awsiam
          ansible-playbook -i localhost, -c local \
          -e "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -e "aws_region=ap-northeast-1" \
          -e "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -e "awsiam_policy_file_path=../iam_policy.json" \
          -e "awsiam_policy_name=${AWSIAM_POLICY_NAME}" \
          -e "awsiam_user=${AWSIAM_USER}" \
          -e "awsiam_user_state=absent" \
          -e "linux_group=runner" \
          -e "linux_user=runner" \
          -e "linux_userhome=/home/runner" \
          install.yml

      - name: Show Go version
        run: |
          go version

      - name: Show Packer version
        run: |
          packer version

      - name: Show Ansible version
        run: |
          ansible --version
